// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlwjKsnRjhvbpE0-me4_UwymLVJSKVX_A',
    appId: '1:624838478202:web:59ccc6aec72911fe9a6ec3',
    messagingSenderId: '624838478202',
    projectId: 'chat-app-riverpod-5b2b5',
    authDomain: 'chat-app-riverpod-5b2b5.firebaseapp.com',
    storageBucket: 'chat-app-riverpod-5b2b5.appspot.com',
    measurementId: 'G-LTWF6VKMJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bIT2DEja24W8uGQuR3SZXHZpfo3ACOg',
    appId: '1:624838478202:android:de8bbfd93bcbfc189a6ec3',
    messagingSenderId: '624838478202',
    projectId: 'chat-app-riverpod-5b2b5',
    storageBucket: 'chat-app-riverpod-5b2b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEDh6iIZ5j8zzeUpfId3XxNkAO6nzjC5E',
    appId: '1:624838478202:ios:2e8d2df74a56ab149a6ec3',
    messagingSenderId: '624838478202',
    projectId: 'chat-app-riverpod-5b2b5',
    storageBucket: 'chat-app-riverpod-5b2b5.appspot.com',
    iosBundleId: 'com.example.chatFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEDh6iIZ5j8zzeUpfId3XxNkAO6nzjC5E',
    appId: '1:624838478202:ios:236f2f081d5e1ad29a6ec3',
    messagingSenderId: '624838478202',
    projectId: 'chat-app-riverpod-5b2b5',
    storageBucket: 'chat-app-riverpod-5b2b5.appspot.com',
    iosBundleId: 'com.example.chatFirebaseApp.RunnerTests',
  );
}
